/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sachy;

import javax.swing.JFrame;

/**
 *
 * @author Lukáš
 */
public class JSachy extends javax.swing.JFrame {
    
    ChessKordinator ChK = ChessKordinator.getChessKordinator();

    /**
     * Creates new form JSachy
     */
    public JSachy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttNovaHra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttNactiHru = new javax.swing.JButton();
        buttZalozSHru = new javax.swing.JButton();
        buttPripoj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttNovaHra.setText("Nová Hra");
        buttNovaHra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttNovaHraActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Šachy v:3.2.0");

        buttNactiHru.setText("Načti Hru");
        buttNactiHru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttNactiHruActionPerformed(evt);
            }
        });

        buttZalozSHru.setText("Založ Server Hru");
        buttZalozSHru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttZalozSHruActionPerformed(evt);
            }
        });

        buttPripoj.setText("Připoj k Server Hře");
        buttPripoj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttPripojActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttNovaHra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttNactiHru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttZalozSHru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttPripoj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(buttNovaHra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttNactiHru, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttZalozSHru, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttPripoj, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttNovaHraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttNovaHraActionPerformed
        Thread t = new Thread(){
            @Override
            public void run(){
                ChK.novaHra();
            }
        };
        t.start();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_buttNovaHraActionPerformed

    private void buttNactiHruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttNactiHruActionPerformed
        Thread t = new Thread(){
            @Override
            public void run(){
                ChK.hrejUlozenouHru();
            }
        };
        t.start();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_buttNactiHruActionPerformed

    private void buttZalozSHruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttZalozSHruActionPerformed
        Thread t = new Thread(){
            @Override
            public void run(){
                ChK.serverHra(true);
            }
        };
        t.start();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_buttZalozSHruActionPerformed

    private void buttPripojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttPripojActionPerformed
        Thread t = new Thread(){
            @Override
            public void run(){
                ChK.serverHra(false);
            }
        };
        t.start();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_buttPripojActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JSachy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JSachy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JSachy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JSachy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JSachy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttNactiHru;
    private javax.swing.JButton buttNovaHra;
    private javax.swing.JButton buttPripoj;
    private javax.swing.JButton buttZalozSHru;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
